### ISSUE TITLE
New package maintenance

### ISSUE THREAD

**Issue by karthik** [ropensci/reol#1]
Package requires some maintenance to bring up to speed with the rest of the suite at some point. 
- [x] `roxygen` documentation
- [x] Travis-CI Integration + Badge
- [ ] Unit tests
- [x] Better readme

**Comment by sckott** [comment]
working on tests now

**Comment by karthik** [comment]
cool! I should be freer next week so delegate stuff to me if you need to.

**Comment by sckott** [comment]
okay, will do, 

more tests to write still

**Comment by maelle** [comment]
This package is no longer maintained and has been archived on CRAN.
