### ISSUE TITLE
Allow MatchTaxatoEOLID to handle multiple search results for a given taxon search

### ISSUE THREAD

**Issue by tdjames1** [ropensci/reol#11]
Sometimes the EOL API returns multiple matches for a taxon even if `exact=TRUE` is specified.
This appears to be due to the presence of unreviewed data associated with the given species name which has been assigned a different EOL ID.

One possible workaround would be to use `filter_by_string` in the [search URL](http://eol.org/api/docs/search) to filter to a specified taxonomic group:

> given a search term, an exact search will be made and that matching page will be used as the taxonomic group against which to filter search results.

E.g. The first search below returns a spurious result along with the correct EOL ID. The other searches return only the correct ID.

http://eol.org/api/search/Anolis%20carolinensis?exact=1
http://eol.org/api/search/Anolis%20carolinensis?exact=1&filter_by_string=Anolis
http://eol.org/api/search/Anolis%20carolinensis?exact=1&filter_by_string=Iguania

**Comment by maelle** [comment]
This package is no longer maintained and has been archived on CRAN.
