### ISSUE TITLE
Validate taxonomic match

### ISSUE THREAD

**Issue by afredstonhermann** [ropensci/reol#5]
Hello! 

I'm trying to find out if a vector of species names from a database I'm using have matches in the EOL database. However, I can't find a function in the Reol documentation that checks for whether or not a taxonomic name is found in EOL. Is there a way to validate a string of species names against the EOL database using Reol, and to isolate the species that are present in EOL, so I can strip data from EOL?

Thank you for developing this tool!

**Comment by sckott** [comment]
@bbanbury @bomeara not sure of best practice for this in this package, thoughts?

EOL is a data source available in the `taxize` package. An e.g., for your use case:

```r
install.packages("taxize")
library("taxize")
nms <- c("Radlkofera calodendron", "Ipomoea plumieriana", "Psoralea archeri")
get_eolid(nms)
#> Retrieving data for taxon 'Radlkofera calodendron'
#> Retrieving data for taxon 'Ipomoea plumieriana'
#> Retrieving data for taxon 'Psoralea archeri'
#> 
#> [1] "59952689" NA         "44270043"
#> attr(,"class")
#> [1] "eolid"
#> attr(,"provider")
#> [1] "NCBI" NA     "GBIF"
#> attr(,"match")
#> [1] "found"     "not found" "found"    
#> attr(,"uri")
#> [1] "http://eol.org/pages/59952689/overview" NA "http://eol.org/pages/44270043/overview"
```

This is a random set of 3 names. You can see how the data sources are actually from NCBI and GBIF in the case of the two names found, as EOL combines data from other sources. One name was not found, so it returned an `NA`, though two names were found with EOL, returning taxon IDs. You can use these Ids to get more info

**Comment by bbanbury** [comment]
Thanks afredstonhermann and Scott for the work around.  I don't think a function exists to check if a taxon exists.  It is a good idea, we can add this as a feature request.  
My work around to this was to download all the taxa and then post process (ie remove) the null files. I used a function similar to this (but note that depending on your system you might have to remove files differently):
```r
PageProcessing <- function(MyEOL, trash=NULL...) {
  res <- xmlToList(xmlRoot(xmlParse(MyEOL, getDTD=FALSE), ...), simplify=FALSE)
  if(!is.null(res$error)) {
    system(paste("mv", MyEOL, trash))
    stop(paste("Bad file", MyEOL, "has been purged"))
    }
  return(res)
}
PageProcessing(list.files(dir), trash="../TRASH/")
```

**Comment by afredstonhermann** [comment]
Great idea @bbanbury and thanks @sckott as well for the input. 

The way I've accomplished this with fishbase and sealifebase (which I'm also using, since this is a marine dataset) is comparing a list of their species (which you can extract with the Rfishbase package) to my species list. Looking through the R taxize documentation - which is a really cool package, thanks for pointing it out! - it seems like it's possible to generate a random list of species names with ```names_list```, but you can't easily extract a string of all the species it can reference.

**Comment by sckott** [comment]
> but you can't easily extract a string of all the species it can reference.

@afredstonhermann can you clarify this point?  What do you mean?

**Comment by afredstonhermann** [comment]
@sckott right now I can get from my dataset, or from fishbase or sealifebase, a list of all the species contained in that dataset that looks like ```"Balaenoptera musculus" "Homerus americanus" "Thunnus thynnus" ... ``` ad nauseam. If it were possible to extract a corresponding list from taxize of all the species it has data for, then using ```intersect``` in ```dplyr``` or something similar I could just identify which species in my dataset have a "match" in taxize.

**Comment by sckott** [comment]
@afredstonhermann `taxize` interacts with lots of different sources of names (see [here](https://github.com/ropensci/taxize#currently-implemented-in-taxize))

All are web APIs, so that makes is such that getting all the names can take a long time. There isn't really an easy way to get all names for each data source in `taxize`. I'm not sure I understand the use case of getting all the names. I imagine you have a set of names you want to match against a taxonomic name source. if so, then just search for those names against that source. Or is there good reason to have a vector of all the names?  `taxize` has many options for taking a set of names and asking if a certain data source has those names. here's a tutorial you could see for egs https://ropensci.org/tutorials/taxize_tutorial.html

You are right that `names_list()` is a good way to get some names. It's purpose is to get a quick set of names for playing/learning how to use `taxize`, and those names are only from one source

**Comment by sckott** [comment]
@afredstonhermann If your concerns are that working with web APIs is too slow, some of the taxonomic databases provide dumps of their data. I have draft functions for working with local database dumps in `taxize` if you are interested let me know

**Comment by maelle** [comment]
This package is no longer maintained and has been archived on CRAN.
