### ISSUE TITLE
Taxonomic data pull

### ISSUE THREAD

**Issue by CharmaneAshbrook** [ropensci/reol#7]
I am trying to pull the entire species data from rfishbase. I successfully pulled the 33,104 records from species_list, but have not been successful with species_names, common_names, synonyms, and sealifebase. My code for species_list is below. Do I need to do something different for these other data frames? --I am doing this because the group I work with regularly uses FAO and RAM Legacy data, as well as NMFS and AFS data. The goal is to create, for every RAM and FAO scientific name, a list of what the scientific name, English name, common name, and synonyms will be for FAO, AFS, NMFS, rfsihbase, and sealifebase.  The FAO dataset is about 12701 species and the RAM dataset has 313 species. 

species_list()
taxaSL <- species_list()
mode(taxaSL)
taxaSL.df <- data.frame(taxaSL)
write.table(taxaSL.df, file="taxaSL.csv", quote=FALSE, row.names = FALSE, col.names = FALSE)

I'll appreciate any help you can provide.

**Comment by sckott** [comment]
hi @CharmaneAshbrook Thanks for your question!   Did you mean to open this in the rfishbase repo? https://github.com/ropensci/rfishbase

**Comment by CharmaneAshbrook** [comment]
I'm not sure what repo is? I'm new to GitHub and found some taxonomic info here so decided to enter my question. Please let me know if you recommend somewhere else--and how to get there!

**Comment by sckott** [comment]
sorry about that. 

repo = "repository" - like this https://github.com/ropensci/reol and this https://github.com/ropensci/rfishbase are repositories or "repos"

the function `species_list` is in `rfishbase` - can you close this issue and open a new issue at https://github.com/ropensci/rfishbase/issues with the same question. 

and thanks again for your question

**Comment by CharmaneAshbrook** [comment]
Thanks! Will do.
